Repository Walingar/java-is-2020, pull requests merged in 2020-05, with the labels that each got.

#14 Add Lab 1 : Another way
  src/main/java/impl/image/ConvolutionProviderFactory.java
  src/main/java/impl/image/ConvolutionProviderImpl.java
  src/main/java/impl/image/ImageConverterFactory.java
  src/main/java/impl/image/ImageConverterImpl.java
Labels: HW1

#116 HW4: Alexey Zhurba
  src/main/java/queue/impl/ArrayQueueFactory.java
  src/main/java/queue/impl/ArrayQueueImpl.java
  src/main/java/queue/impl/LinkedQueueFactory.java
  src/main/java/queue/impl/LinkedQueueImpl.java
Labels: HW4

#126 HW6: Smirnov Kirill
  src/main/java/impl/pair/NumberPairFactory.java
  src/main/java/impl/pair/NumberPairImpl.java
  src/main/java/impl/pair/PairFactory.java
  src/main/java/impl/pair/PairImpl.java
Labels: HW6

#137 HW6: Kutimskiy Maxim
  src/main/java/impl/pair/NumberPairFactory.java
  src/main/java/impl/pair/NumberPairImpl.java
  src/main/java/impl/pair/PairFactory.java
  src/main/java/impl/pair/PairImpl.java
Labels: HW6
