Repository Walingar/java-is-2020, pull requests merged in 2020-06, with the labels that each got.

#168 HW1: Stepanov Sergey
  src/main/java/impl/image/ConvolutionProviderFactory.java
  src/main/java/impl/image/ConvolutionProviderImpl.java
  src/main/java/impl/image/ImageConverterFactory.java
  src/main/java/impl/image/ImageConverterImpl.java
Labels: HW1

#129 HW3: Alex Ivchenko
  src/main/java/impl/weather/ImmutableDayTemperatureInfo.java
  src/main/java/impl/weather/YearTemperatureStatsFactory.java
  src/main/java/impl/weather/YearTemperatureStatsImpl.java
  src/main/java/impl/weather/YearTemperatureStatsParserFactory.java
  src/main/java/impl/weather/YearTemperatureStatsParserImpl.java
Labels: HW3

#130 HW4: Alex Ivchenko
  src/main/java/queue/impl/ArrayQueueFactory.java
  src/main/java/queue/impl/IntArrayQueue.java
  src/main/java/queue/impl/IntLinkedQueue.java
  src/main/java/queue/impl/LinkedQueueFactory.java
Labels: HW4

#143 HW5: Alex Ivchenko
  src/main/java/impl/file/FileEncodingReaderFactory.java
  src/main/java/impl/file/FileEncodingReaderImpl.java
  src/main/java/impl/file/FileEncodingWriterFactory.java
  src/main/java/impl/file/FileEncodingWriterImpl.java
Labels: HW5

#187 HW6: Stepanov Sergey
  src/main/java/impl/pair/NumberPairFactory.java
  src/main/java/impl/pair/NumberPairImpl.java
  src/main/java/impl/pair/PairFactory.java
  src/main/java/impl/pair/PairImpl.java
Labels: HW6

#184 HW5: Yushchuk Alexey
  src/main/java/impl/file/FileEncodingReaderFactory.java
  src/main/java/impl/file/FileEncodingReaderImpl.java
  src/main/java/impl/file/FileEncodingWriterFactory.java
  src/main/java/impl/file/FileEncodingWriterImpl.java
Labels: HW5

#172 HW:2 Andrew Korzhov
  src/main/java/impl/expression/ExpressionParserFactory.java
  src/main/java/impl/expression/ExpressionParserImpl.java
Labels: HW2

#193 HW4: Vorontsov Andrey
  src/main/java/queue/impl/ArrayQueueFactory.java
  src/main/java/queue/impl/ArrayQueueImpl.java
  src/main/java/queue/impl/LinkedQueueFactory.java
  src/main/java/queue/impl/LinkedQueueImpl.java
Labels: HW4

#92 HW7: Chausov Andrey
  src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
  src/main/java/info/kgeorgiy/java/advanced/student/StudentQueryFactory.java
Labels: HW7

#145 HW7: Alex Ivchenko
  src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
  src/main/java/info/kgeorgiy/java/advanced/student/StudentQueryFactory.java
Labels: HW7

#190 HW7: Yushchuk Alexey
  src/main/java/info/kgeorgiy/java/advanced/student/StudentDB.java
  src/main/java/info/kgeorgiy/java/advanced/student/StudentQueryFactory.java
Labels: HW7

#160 HW8: Titova Anastasiia
  src/main/java/impl/matrix/ParallelMultiplierFactory.java
  src/main/java/impl/matrix/ParallelMultiplierImpl.java
Labels: HW8

#161 HW8: Saravayskiy Mike
  src/main/java/impl/matrix/ParallelMultiplierFactory.java
  src/main/java/impl/matrix/ParallelMultiplierImpl.java
Labels: HW8

#165 HW8: Alex Ivchenko
  src/main/java/impl/matrix/ParallelMultiplierFactory.java
  src/main/java/impl/matrix/ParallelMultiplierImpl.java
Labels: HW8

#223 HW8: Chausov Andrey
  src/main/java/impl/matrix/Matrix.java
  src/main/java/impl/matrix/ParallelMultiplierFactory.java
  src/main/java/impl/matrix/ParallelMultiplierImpl.java
Labels: HW8

#213 HW8: Danil Ivanov
  src/main/java/impl/matrix/ParallelMultiplierFactory.java
  src/main/java/impl/matrix/ParallelMultiplierImpl.java
Labels: HW8

#214 HW8: Maxim Kutimskiy
  src/main/java/impl/matrix/ParallelMultiplierFactory.java
  src/main/java/impl/matrix/ParallelMultiplierImpl.java
Labels: HW8

#221 HW: 8 Mednikov Artem
  src/main/java/impl/matrix/ParallelMultiplierFactory.java
  src/main/java/impl/matrix/ParallelMultiplierImpl.java
Labels: HW8

#169 HW9: Titova Anastasiia
  src/main/java/impl/network/FollowersStatsFactory.java
  src/main/java/impl/network/FollowersStatsImpl.java
Labels: HW9

#175 HW9: Alex Ivchenko
  src/main/java/impl/network/FollowersStatsFactory.java
  src/main/java/impl/network/FollowersStatsImpl.java
Labels: HW9

#211 HW9: Stepanov Sergey
  src/main/java/impl/network/FollowersStatsFactory.java
  src/main/java/impl/network/FollowersStatsImpl.java
Labels: HW9

#216 HW9: Danil Ivanov
  src/main/java/impl/network/FollowersStatsFactory.java
  src/main/java/impl/network/FollowersStatsImpl.java
Labels: HW9

#219 HW9: Leonova Elizaveta
  src/main/java/impl/network/FollowersStatsFactory.java
  src/main/java/impl/network/FollowersStatsImpl.java
Labels: HW9

#226 HW9: Chausov Andrey
  src/main/java/impl/network/FollowersStatsFactory.java
  src/main/java/impl/network/FollowersStatsImpl.java
Labels: HW9

#208 HW:8 Korzhov Andrew
  src/main/java/impl/matrix/ParallelMultiplierFactory.java
  src/main/java/impl/matrix/ParallelMultiplierImpl.java
Labels: HW8

#106 HW4: Kuklin Dmitrii
  src/main/java/queue/factory/LinkedQueueFactory.java
  src/main/java/queue/impl/ArrayQueueImpl.java
  src/main/java/queue/impl/LinkedQueueImpl.java
  src/main/java/queue/impl/linked/LinkedQueueImpl.java
  src/main/java/queue/impl/linked/LinkedQueueIterator.java
  src/main/java/queue/impl/linked/Node.java
Labels: HW4

#178 HW5: Danil Shayakhmetov
  README.md
  gradlew.bat
  src/main/java/api/file/FileEncodingException.java
  src/main/java/impl/file/FileEncodingReaderFactory.java
  src/main/java/impl/file/FileEncodingReaderImpl.java
  src/main/java/impl/file/FileEncodingWriterFactory.java
  src/main/java/impl/file/FileEncodingWriterImpl.java
Labels: HW5

#141 HW6: Kuklin Dmitrii
  src/main/java/api/pair/Pair.java
  src/main/java/factory/pair/NumberPairImpl.java
  src/main/java/factory/pair/PairImpl.java
  src/main/java/impl/pair/NumberPairFactory.java
  src/main/java/impl/pair/PairFactory.java
Labels: HW6

#157 HW7: Danil shayakhmetov
  README.md
  src/main/java/info/kgeorgiy/java/advanced/student/StudentDb.java
  src/main/java/info/kgeorgiy/java/advanced/student/StudentQueryFactory.java
Labels: HW7

#227 HW8: Danil shayakhmetov
  README.md
  src/main/java/impl/matrix/ParallelMultiplierFactory.java
  src/main/java/impl/matrix/ParallelMultiplierImpl.java
Labels: HW8
